# Generated by Django 5.0.7 on 2024-07-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
