# Generated by Django 5.0.7 on 2024-07-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_alter_post_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
