# Generated by Django 5.0.7 on 2024-07-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_user_used_pdfhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfhistory',
            name='image',
            field=models.CharField(max_length=999999999999999999999999999999999999999),
        ),
    ]
